### ISSUE TITLE
Any interest in joining inspect-js?

### ISSUE THREAD

**Issue by ljharb** [inspect-js/has-object-spread#2]
This package exactly fits with the other “environment detection” packages in the https://github.com/inspect-js GitHub/npm org. Would you be interested in moving the repo?

**Comment by goto-bus-stop** [comment]
sure! is there also an npm org that i could grant ownership?

**Comment by ljharb** [comment]
Yes! I’ll invite you to both orgs

**Comment by goto-bus-stop** [comment]
I think I'm not allowed to add the package to the `inspect-js:developers` team on npm. i just added you as an owner instead

**Comment by ljharb** [comment]
Thanks, I’ll add it to the proper teams. Welcome!
